# Generated by Django 3.1.7 on 2021-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210328_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calorie_goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='userfoodstorage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='userfoodstorage',
            unique_together=set(),
        ),
    ]
