# Generated by Django 3.1.7 on 2021-04-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210410_0825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fooditem',
            unique_together=set(),
        ),
    ]
