# Generated by Django 3.1.7 on 2021-04-24 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210417_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_food',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_storage', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='food_items',
            field=models.ManyToManyField(related_name='food', to='profiles.FoodItem'),
        ),
        migrations.DeleteModel(
            name='UserFoodStorage',
        ),
    ]
