# Generated by Django 3.1.7 on 2021-04-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210424_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='food_items',
        ),
        migrations.AddField(
            model_name='profile',
            name='food_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='profiles.fooditem'),
        ),
    ]
