# Generated by Django 3.1.7 on 2021-04-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210426_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='food_items',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
