# Generated by Django 3.1.7 on 2021-03-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('food_group', models.CharField(choices=[('f', 'Fruits'), ('v', 'Vegetables'), ('g', 'Grains'), ('p', 'Protein Foods'), ('d', 'Dairy')], max_length=2)),
                ('carbohydrates', models.FloatField()),
                ('fats', models.FloatField()),
                ('protein', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('standard_portion', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_storage.foodcategory')),
            ],
        ),
    ]
