# Generated by Django 3.1.7 on 2021-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterModelOptions(
            name='foodingredient',
            options={'verbose_name': 'Ingredients'},
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
