# Generated by Django 3.1.7 on 2021-03-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_storage', '0002_auto_20210328_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodingredient',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ingredients', to='food_storage.foodcategory'),
        ),
    ]
