# Generated by Django 3.1.7 on 2021-03-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_storage', '0003_auto_20210328_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodingredient',
            options={'verbose_name': 'Ingredient'},
        ),
    ]
