# Generated by Django 3.1.7 on 2021-04-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_storage', '0004_auto_20210328_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
