# Generated by Django 3.1.7 on 2021-04-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_storage', '0005_auto_20210411_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodingredient',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ingredients', to='food_storage.foodcategory'),
        ),
        migrations.AlterField(
            model_name='foodingredient',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='foodingredient',
            name='standard_portion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
