from django.urls import path

from profiles import views

app_name = "profiles"
urlpatterns = [
    path('', views.index, name="index"),

    path('profile-create/',
         views.ProfileCreateView.as_view(),
         name="profile-create"),
    path('profile-list/',
         views.ProfileListView.as_view(),
         name="profile-list"),
    path('profile-detail/<pk>/',
         views.ProfileDetailView.as_view(),
         name="profile-detail"),
    path('profile-update/<pk>/',
         views.ProfileUpdateView.as_view(),
         name="profile-update"),
    path('profile-delete/<pk>/',
         views.ProfileDeleteView.as_view(),
         name="profile-delete"),
    
    path('food_item-create/',
         views.FoodItemCreateView.as_view(),
         name="food_item-create"),
    path('food_item-list/',
         views.FoodItemListView.as_view(),
         name="food_item-list"),
    path('food_item-detail/<pk>/',
         views.FoodItemDetailView.as_view(),
         name="food_item-detail"),
    path('food_item-update/<pk>/',
         views.FoodItemUpdateView.as_view(),
         name="food_item-update"),
    path('food_item-delete/<pk>/',
         views.FoodItemDeleteView.as_view(),
         name="food_item-delete"),
    
    path('food_storage-create/',
         views.UserFoodStorageCreateView.as_view(),
         name="food_storage-create"),
    path('food_storage-create/prof/<prof_id>',
         views.UserFoodStorageCreateView.as_view(),
         name="food_storage-w-prof-create"),
    path('food_storage-list/',
         views.UserFoodStorageListView.as_view(),
         name="food_storage-list"),
    path('food_storage-detail/<pk>/',
         views.UserFoodStorageDetailView.as_view(),
         name="food_storage-detail"),
    path('food_storage-update/<pk>/',
         views.UserFoodStorageUpdateView.as_view(),
         name="food_storage-update"),
    path('food_storage-delete/<pk>/',
         views.UserFoodStorageDeleteView.as_view(),
         name="food_storage-delete"),
]
