# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Collect Static
      run: python manage.py collectstatic
      env: 
        DEBUG: "False"
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: "*"
        DATABASE_URL: "postgres://postgres:password@127.0.0.1:5432/postgres"
    - name: Run tests
      run: python manage.py test
      env:
        DEBUG: "False"
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: "*"
        DATABASE_URL: "postgres://postgres:password@127.0.0.1:5432/postgres"
        
        
